// Generated by CoffeeScript 1.11.1
(function() {
  var cols, getShortestColumn;

  cols = [$('#articles_col_0'), $('#articles_col_1'), $('#articles_col_2')];

  getShortestColumn = function() {
    var heights, shortest, shortestIndex;
    heights = [$('#articles_col_0').height(), $('#articles_col_1').height(), $('#articles_col_2').height()];
    shortest = null;
    shortestIndex = 0;
    heights.forEach(function(height, idx) {
      if (shortest === null || shortest > height) {
        shortest = height;
        return shortestIndex = idx;
      }
    });
    return shortestIndex;
  };

  $('#temp_col > .article').each(function(idx, article) {
    return cols[getShortestColumn()].append(article);
  });

}).call(this);

//# sourceMappingURL=1_4_2_faq.js.map
